4 authentication
GuildCrafts/lizardboard pull request #14
Opened 2016-11-01 22:55 UTC by Moniarchy

-set up POST/register and POST/login routes in index.js file
-set up GET/logout route in index.js file
-created login and register views

2016-11-03 22:00 UTC, Moniarchy commented
@jrob8577 we think this is ready for review.

2016-11-03 22:09 UTC, jrobcodes requested changes
@shakalee14 @Moniarchy Changes requested.

2016-11-03 22:09 UTC, jrob8577 commented on app.js
> +const routes = require('./routes/index');
Can we rename `routes` here?  I always find this initial naming convention from express-generator confusing...

2016-11-03 22:09 UTC, jrob8577 commented on app.js
> +passport.use(new localStrategy(Account.authenticate()));
Can we move the passport setup out into another module? (See floworky for an example)

2016-11-03 22:09 UTC, jrob8577 commented on app.js
>  // app.use(express.static(buildpath+'/public'))
Why is this commented out?

2016-11-03 22:09 UTC, jrob8577 commented on database/db.js
> +const MongoClient = require('mongodb').MongoClient, assert = require('assert');
remove `assert`, it's not being used

2016-11-03 22:09 UTC, jrob8577 commented on database/db.js
> +const db = 'mongodb://localhost/lizardboard'
rename `db`

2016-11-03 22:09 UTC, jrob8577 commented on database/db.js
> +const url = 'mongodb://127.0.0.1:27017/lizardboard';
Why are there two connection strings?

2016-11-03 22:09 UTC, jrob8577 commented on routes/index.js
> +  Account.register(new Account({ username : request.body.username }),
I thought we refactored this to make it more readable?

2016-11-16 18:17 UTC, Moniarchy commented
Closing this PR because @shakalee14 and their partner are working on this anew.

2016-11-16 18:17 UTC, closed without merging