4-authentication
GuildCrafts/lizardboard pull request #43
Opened 2016-11-16 22:28 UTC by shakalee14

implemented 3 authenticated endpoints: register, login, logout

2016-11-16 23:48 UTC, jrobcodes requested changes
@shakalee14 @shengdzhang Comments inline

2016-11-16 23:48 UTC, jrob8577 commented on app.js
> +const appRoot = process.env.APP_ROOT
what is `appRoot` used for?

2016-11-16 23:48 UTC, jrob8577 commented on app.js
> +app.use(( request, response, next ) => {
Let's define this as middleware in another file to help keep this file clean:
```js
const cors = ( request, response, next ) => {
  // all the things
  next()
}
```
Then we can import this as `cors` in `app.js` and:
```js
const cors = require( './src/cors' ) // or whatever
app.use( cors )
```

2016-11-16 23:48 UTC, jrob8577 commented on config/passport.js
> +const JwtStrategy = require( 'passport-jwt' ).Strategy
Let's change these two lines to one:
```js
const { Strategy, ExtractJwt } = require( 'passport-local' )
```

2016-11-16 23:48 UTC, jrob8577 commented on config/passport.js
> +      if ( error ) { return done(error); }
Please no single line if statements

2016-11-16 23:48 UTC, jrob8577 commented on config/passport.js
> +
Remove this whitespace

2016-11-16 23:48 UTC, jrob8577 commented on config/passport.js
> +  secretOrKey: 'super secret passphrase'
this secret needs to come from `process.env.SECRET`, and have a corresponding key set in the .env file.  See @Moniarchy and @jessehall3 work for how to accomplish this.

2016-11-16 23:48 UTC, jrob8577 commented on database/database.js
> +const mongoose = require( 'mongoose' )
Let's remove this file - I don't think we need it for anything?

2016-11-16 23:48 UTC, jrob8577 commented on models/users.js
> +   token: {type: String},
Please add spaces between braces and key/value pairs:
```js
token: { type: String }
```

2016-11-16 23:48 UTC, jrob8577 commented on models/users.js
> +  if ( !user.isModified( 'password' )) return next();
No single line ifs

2016-11-16 23:48 UTC, jrob8577 commented on models/users.js
> +
Reomve this new line

2016-11-16 23:48 UTC, jrob8577 commented on models/users.js
> +
Rmove this whitespace

2016-11-16 23:48 UTC, jrob8577 commented on models/users.js
> +module.exports = mongoose.model('User', UserSchema);
spaces between parens and arguments

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/login.js
> +  return jwt.sign( user, 'super secret passphrase', {
`super secret passphrase` should be read in from `process.env`

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/login.js
> +    expiresIn: 10080
Why 10080?

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/register.js
> +const generateToken = user => {
Refactor all of the code duplicated between this file and `login.js` into its own module, so that we are not duplicating functionality.

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/register.js
> +  const email = request.body.email
```js
const { email, password } = request.body
```

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/register.js
> +    return response.status(422).send({ error: 'You must enter an email address.' })
spaces between parens and args

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/register.js
> +        return response.status(422).send({ error: 'That email address is already in use.' })
Spaces between parens and args, please use a more generic error message (we don't want to give hackers the ability to test until they find a valid email address)

2016-11-16 23:48 UTC, jrob8577 commented on src/authentication/register.js
> +        return response.status(201).json( tokenInfo( user ))
Spaces between parens and args

2016-11-17 00:15 UTC, shakalee14 commented on database/database.js
> +const mongoose = require( 'mongoose' )
we can move this to app.js but we need it to connect to the right database

2016-11-17 00:16 UTC, jrob8577 commented on database/database.js
> +const mongoose = require( 'mongoose' )
Ah - I think it's in bin/www in @Moniarchy and @jessehall3 branch

2016-11-17 00:34 UTC, shakalee14 commented on src/authentication/login.js
> +    expiresIn: 10080
its 2.8hrs we believe....

2016-11-18 00:17 UTC, jrobcodes requested changes
@shakalee14 @shengdzhang Comments inline

2016-11-18 00:17 UTC, jrob8577 commented on bin/www
> +mongoose.connect( 'mongodb://127.0.0.1:27017/lizardboard' )
This should be using the `process.env` variable from master?

2016-11-18 00:17 UTC, jrob8577 commented on config/passport.js
> +      if ( error ) {
Please omit spaces between keywords and opening parens.

2016-11-18 00:17 UTC, jrob8577 commented on config/passport.js
> +      if ( !isMatch ) {
Please omit spaces between keywords and opening parens.

2016-11-18 00:17 UTC, jrob8577 commented on config/passport.js
> +passport.use(jwtLogin)
Please add spaces between parens and arguments.

2016-11-18 00:17 UTC, jrob8577 commented on config/passport.js
> +const jwtLogin = new Strategy( jwtOptions, function( payload, done ) {
Was this the place that couldn't be an ES6 function?

2016-11-18 00:17 UTC, jrob8577 commented on models/users.js
> +<<<<<<< HEAD
Merge conflict in your submission...

2016-11-18 00:17 UTC, jrob8577 commented on models/users.js
> +  if ( !user.isModified( 'password' )){
Please omit spaces between keywords and opening parens.

2016-11-18 00:17 UTC, jrob8577 commented on models/users.js
> +    if ( err ) return next( err )
Please omit spaces between keywords and opening parens.  No single line if statements.

2016-11-18 00:17 UTC, jrob8577 commented on models/users.js
> +      if ( err ) return next(err)
Please omit spaces between keywords and opening parens. No single line if statements.

2016-11-18 00:17 UTC, jrob8577 commented on models/users.js
> +<<<<<<< HEAD
Merge conflict committed...

2016-11-18 00:17 UTC, jrob8577 commented on src/authentication/authmethods.js
> +const jwt = require( 'jsonwebtoken' )
Please do not use abbreviated terms in names - I suggest renaming this file `authentication.js`, or simply `index.js` if it's the only file in this directory

2016-11-18 00:17 UTC, jrob8577 commented on src/authentication/register.js
> +  User.findOne({ email: email }, (err, existingUser) => {
Spaces between parens and args

2016-11-18 00:17 UTC, jrob8577 commented on src/authentication/register.js
> +  if (!email) {
Spaces between parens and args, please omit spaces between keywords and opening parens.

2016-11-18 16:48 UTC, shakalee14 commented on config/passport.js
> +const jwtLogin = new Strategy( jwtOptions, function( payload, done ) {
We can't use es6 when we are using 'this' because it changes the scope.

2016-11-18 18:02 UTC, jrobcodes requested changes
@shakalee14 @shengdzhang Many formatting issues remain; comments inline

2016-11-18 18:02 UTC, jrob8577 commented on app.js
> +  app.use( (err, req, res, next) => {
Why are these lines changed? (let's revert this change so we're not adding diffs that are not related to our current feature implementation)

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +
Please group library imports together at the top of the module, with no whitespace.  Project modules should be separated from library imports by whitespace:
```js
const passport = require( 'passport' )
const LocalStrategy = require( 'passport-local' )
const { Strategy, ExtractJwt } = require( 'passport-jwt' )

const User = require( '../models/users' )
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +const localOptions = {
This should be named using standard naming conventions for constants: `LOCAL_OPTIONS` (and updated below)

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +    if(error) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +    if(!user) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +      if(error) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +      if(!isMatch) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +const localLogin = new LocalStrategy( localOptions, strategy )
Please move these declarations of objects to the top of the module - the flow of the module should be:
* library imports
* imports 
* declarations
* functions
* exports

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +  User.findById(payload._id, function( err, user ) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +    if (err) { return done(err, false) }
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```
Please do not use single line control flow, and always include braces:
```js
if(expression) return thing;
```
should be
```js
if( expression ) {
  return thing;
}
```

2016-11-18 18:02 UTC, jrob8577 commented on config/passport.js
> +    if (user) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on models/users.js
> +   email: { type: String, required: true, unique: true },
Was it an intentional omission to remove `name` and `username`?

2016-11-18 18:02 UTC, jrob8577 commented on models/users.js
> +  if (!user.isModified( 'password' )){
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on models/users.js
> +    if (err)
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```
Please do not use single line control flow, and always include braces:
```js
if(expression) return thing;
```
should be
```js
if( expression ) {
  return thing;
}
```

2016-11-18 18:02 UTC, jrob8577 commented on models/users.js
> +      if (err)
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```
Please do not use single line control flow, and always include braces:
```js
if(expression) return thing;
```
should be
```js
if( expression ) {
  return thing;
}
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/authentication.js
> +  return jwt.sign( user, 'super secret passphrase', {
The passphrase should be in the `process.env`

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +  if (!email) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +  console.log('email', email )
Remove `console.log`

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +exports.register = (request, response, next) => {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +  User.findOne({ email: email }, (err, existingUser) => {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +      if (err){
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +        return next(err)
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +      if (existingUser) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +        return response.status(422).send({ error: ERROR_MESSAGE })
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +        if(err) {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:02 UTC, jrob8577 commented on src/authentication/register.js
> +        return response.status(201).json( tokenInfo( user ) )
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 18:06 UTC, shakalee14 commented on models/users.js
> +   email: { type: String, required: true, unique: true },
yes

2016-11-18 19:30 UTC, jrobcodes requested changes
@shakalee14 @shengdzhang Just a few more things...

2016-11-18 19:30 UTC, jrob8577 commented on config/passport.js
> +
Remove extraneous whitespace

2016-11-18 19:30 UTC, jrob8577 commented on config/passport.js
> +  User.findById(payload._id, function( err, user ) {
This comment was not addressed (space before `payload` please)

2016-11-18 19:30 UTC, jrob8577 commented on models/users.js
> +
Remove extraneous whitespace

2016-11-18 19:30 UTC, jrob8577 commented on routes/api/v1/users.js
> +  response.send('User has logged out')
We should not be sending strings from the API, we should be sending a status code.

2016-11-18 19:51 UTC, jrobcodes requested changes
@shakalee14 @shengdzhang

2016-11-18 19:51 UTC, jrob8577 commented on models/users.js
> +  bcrypt.compare(candidatePassword, this.password, ( error, isMatch ) => {
Please add spaces between opening and closing parentheses, and arguments, in a function invocation or control flow expression:
```js
fn(param1, param2) { /* ... */ }
if(expression) { /* ... */ }
```
should be
```js
fn( params1, param2 ) { /* ... */ }
if( expression ) { /* ... */ }
```

2016-11-18 19:53 UTC, shakalee14 commented on models/users.js
> +  bcrypt.compare(candidatePassword, this.password, ( error, isMatch ) => {
ok :)

2016-11-18 19:56 UTC, jrobcodes requested changes
Sorry, missed that last thing.  That last last thing. @shakalee14

2016-11-18 19:56 UTC, jrob8577 commented on routes/api/v1/users.js
> +  response.send( 200 )
```js
response.status( 200 )
```

2016-11-18 20:00 UTC, jrobcodes approved these changes

2016-11-18 20:03 UTC, merged